
def write_ply(path, vertices):
    f = open(path,"w")
    f.write("""ply
format ascii 1.0
comment generated by write_ply
element vertex {0}
property float x
property float y
property float z
end_header
""".format(len(vertices)))
    for vertex in vertices:
        f.write("{0} {1} {2}\n".format(vertex[0],vertex[1],vertex[2]))
    f.close()


if __name__ == '__main__':
    v = [(0,0,0),
         (1,1,1),
         (2,0,10)]
    write_ply('test.ply',v)
